version: '3'
services:
  webapp:
    build: .
    volumes:
      - .:/lab02
    ports:
      - 3000:3000
    container_name: lab02
    links:
      - lab02_db
    command: sh /lab02/scripts/startup.sh
    env_file: .env
  lab02_db:
    image: postgres
    container_name: lab02_db
    env_file: .env
