version: '3'
services:
  lab02:
    build: .
    volumes:
      - .:/lab02
    ports:
      - 3000:3000
    container_name: lab02
    links:
      - db
    command: sh /lab02/scripts/startup.sh
    env_file: .env
  db:
    image: postgres
    container_name: db
    env_file: .env
